const Courses=[
    {
    id:1,
    title:"Web Development",
    image:require("../../assets/web.png"),
    description:"Web development is the work involved in developing a website for the Internet or an intranet. Web development can range from developing a simple single static page of plain text to complex web applications.",
    course1:"HTML",
    course2:"CSS",
    course3:"JavaScript",
    price:4999,
},
{
    id:2,
    title:"Java Full Course",
    image:require("../../assets/java.png"),
    description:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
    course1:"Java",
    course2:"J2EE",
    course3:"Sql",
    price:5000,
},
{
    id:3,
    title:"FullStack Developer",
    image:require("../../assets/fullstack.jpg"),
    description:"A full-stack developer is a developer or engineer who can build both the front end and the back end of a website. The front end and the back end require different skill sets.",
    course1:"HTML",
    course2:"CSS",
    course3:"JavaScript & Nodejs",
    price:4500,
},
{
    id:4,
    title:"Python Full Courses",
    image:require("../../assets/python.png"),
    description:"Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage-collected.",
    course1:"Python",
    course2:"Pandas",
    course3:"Sql",
    price:4000,
},
{
    id:5,
    title:"DotNet Full Courses",
    image:require("../../assets/dotnet.png"),
    description:". NET Developer is a professional who builds software applications using languages and technologies of the . NET framework. They are responsible for designing, coding, testing, and deploying applications.",
    course1:"C#",
    course2:".Net",
    course3:"JavaScript",
    price:5500,
},
{
    id:6,
    title:"AI Full Courses",
    image:require("../../assets/AI.png"),
    description:"Artificial intelligence is the intelligence of machines or software, as opposed to the intelligence of other living beings, primarily of humans. It is a field of study in computer science that develops and studies intelligent machines.",
    course1:"Data Science",
    course2:"Python",
    course3:"AI & ML",
    price:7000,
},
]

export default Courses;